"""empty message

Revision ID: a3b6c8065a7d
Revises: 0af16f4f1da1
Create Date: 2021-02-19 19:10:59.883799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b6c8065a7d'
down_revision = '0af16f4f1da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_artist.id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.drop_column('show', 'artist.id')
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.add_column('show', sa.Column('artist.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_artist.id_fkey', 'show', 'artist', ['artist.id'], ['id'])
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
